# Generated by Django 4.2 on 2023-04-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
