# Generated by Django 4.2 on 2023-04-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_crew',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
