# Generated by Django 4.2 on 2023-04-15 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0019_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('menu_item', 'user')},
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
